services:
  redis:
    image: redis:8.2-alpine
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - safir-redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

volumes:
  safir-redis-data:
